version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: book-dbs
    ports: [ "5432:5432" ]
    env_file: [ .env ]
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  
  redis:
    container_name: book-redis
    platform: linux/x86_64
    image: docker.io/bitnami/redis:7.0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - redis-network
    env_file: [ .env ]

  redis-commander:
    container_name: book-redis-commander
    image: rediscommander/redis-commander:latest
    platform: linux/x86_64
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports: [ "29094:8081" ]
    networks:
      - redis-network
    env_file: [ .env ]

volumes:
  redis_data:
    driver: local
networks:
  redis-network:
    driver: bridge